from .account_views import *
from .authentication_views import *
from .dashboard_view import *
from .delete_upload_view import *
from .file_list_view import *
from .mixins import *
from .notification_view import *
from .share_file_view import *
from .static_views import *
from .test_view import *
from .team_view import *
