# Generated by Django 4.2.6 on 2024-02-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme_preference',
            field=models.CharField(default='default-mode', max_length=30),
        ),
    ]
