# Generated by Django 4.2.6 on 2024-03-26 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='upload',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tasks.upload'),
            preserve_default=False,
        ),
    ]
