# Generated by Django 4.2.6 on 2024-03-26 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_notification_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='shared_file_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.sharedfiles'),
        ),
    ]
