# Generated by Django 4.2.6 on 2024-03-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
