# Generated by Django 4.2.6 on 2024-03-10 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tasks.models.voice_comment


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_pdfinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to=tasks.models.voice_comment.user_directory_path)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.upload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pdfinfo',
            name='comments',
            field=models.ManyToManyField(to='tasks.voicecomment'),
        ),
    ]
