# Generated by Django 4.2.6 on 2024-02-09 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_upload_sharedfiles_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharedfiles',
            old_name='date',
            new_name='shared_date',
        ),
    ]
