# Generated by Django 4.2.6 on 2024-03-05 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_pdfmark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdfmark',
            old_name='markId',
            new_name='mark_id',
        ),
    ]
