# Generated by Django 4.2.6 on 2024-02-17 14:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_notification_notification_message_notification_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='comments',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='theme_preference',
            field=models.CharField(default='default-mode', max_length=30),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('shared_uploads', models.ManyToManyField(to='tasks.upload')),
            ],
        ),
    ]
