# Generated by Django 4.2.6 on 2024-02-03 23:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='time_of_notification',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
