# Generated by Django 4.2.6 on 2024-03-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_pdfmark_listofspans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfmark',
            name='listOfSpans',
            field=models.JSONField(),
        ),
    ]
