# Generated by Django 4.2.6 on 2024-03-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_pdfmark_listofspans'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfmark',
            name='listOfComments',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
