# Generated by Django 4.2.6 on 2024-03-06 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_pdfmark_listofcomments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfmark',
            name='listOfMarks',
        ),
    ]
