# Generated by Django 4.2.6 on 2024-03-06 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_pdfmark_listofmarks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PDFMark',
            new_name='PDFInfo',
        ),
    ]
